plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\lovet\\Downloads\\TerraRun\\TerraRun\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build:web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]